knp_snappy:
    pdf:
        enabled:    true
        binary:     '%env(SNAPPY_PDF_BINARY)%'
        options:    []
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
