vich_uploader:
    db_driver: orm

    mappings:
       image_directory:
            uri_prefix: '%image_directory'
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
